version: 2
updates:
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "daily"
      rebase-strategy: "disabled"
      target-branch: dev

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      rebase-strategy: "disabled"
      target-branch: dev
