#!/bin/bash

export ORG_GRADLE_PROJECT_signingInMemoryKey="-----BEGIN PGP PRIVATE KEY BLOCK-----

                                              lQdGBGALlkMBEACylr5wF2VcrQxNThHKSj5gMYoDK3D7RdzCJn+qbmZzPcnn7sOA
                                              pXWhohSKt5HqhL17cbC/2Weg1oXhfwRW0VansLZW8xz314F34vbpr8NW+QsY8Jt4
                                              t09L+pBlySPjqR4AaHdC3Zd/5jIsR3lVkhhfrO0+HWFXQlJaDR8Z6OVFkIXDsYxI
                                              uFe5rWGj87SShopewgeqrc2syDAQnG4jzG5/5Ys6WmeehNBiVtwnFnrUQuSf169T
                                              8nBhpwHhKyhTHGu4qhJ5kMAgfoYOxFFMPDheRkeBoMouhLjIFPe+ytul8m0P0fK+
                                              cRXVKXmyL/7Ofi9mUY4umOOqVFPOhzcfZPMFLVqAFaAmVhGbE1gVgfnltD9THiHz
                                              +mzTCI/BXsWpzMdQCpcrnPmOm/OPQGpZK5pE1ArKx4bxOXeIKm3rU+3Ueutq909p
                                              S9Pjgp1F9lFIW5zOZwzELqG/ZELEFralfGWXlWf2kch6ARydxFMyGmTE3SbedFKK
                                              nix/nn7SYoS05lUpVv4CIVEIfgq3KK5XolQ9fgJUg0F5aabvQyOzHn21hzDN2XWh
                                              ccY7yHbYnmVvOW2+kSjpjg6EaaQuN9QZyBvTS92FbpimtCXbfr6Fsg1oDMEHg0Dx
                                              lh7ls/NkP4zEAjMKfzX9dtioJHLllPv5rqLIurk7cazMD5IFp9vx2AqiAwARAQAB
                                              /gcDAs91nO/WVwiY4rwAUXNStaHxlTnwCKdI4EYOvQAMeRfHU73NvTzteXrgMQZg
                                              kP5yS6HyyV8tOSawMIl4AJgrJPNTfC14BS7GPgPGyNWaSqJL5VrpFQwzCvNV9RD3
                                              aYMCk9HQJaWH5w4QKrnx0Lu8tOG9Huw7n7TnUirI7zOiDM8adGDQstae3eNYGdXr
                                              sIY08mGbv+bGAwqBoUbvv3ZAqgbdnqp7URcuCtyPNeyY2yc8WZdeLO61KJbUFcme
                                              L9/GgYV7JpHIUHGs+JnEjprEveNvIw/U+22v/aV8GBDR8W1UhIM2r1J/5to5MPjG
                                              xz3azH71JeQqIb8Yf6t7eMTmllUlLLPkYqLDQA9BFq5dNTQZBHCbzVbvfHzmI5cC
                                              TNm0HUb0WE9CoNjmEB0QuXCUJwMVKQCdvHKW4SENKZK+bctwY01q9uY0HQ5Nq+u2
                                              If1WbMbg03L1DErW4UHLkRk0b2gt6qD81imua2z81eLWajrQFAIDRfUsVHGGF7w5
                                              UxEFzhhW6zU9XJlBYj3ALU0iase4zjFwQyvAvG6gyRVrTrbt/J0fXSrqdlbi2bpE
                                              PFosxaQadO76fFl/R+fyz1zWk5kBc+/dVYqgPnXiMweQvz5aQsvb22TSHitdcWBJ
                                              KW0j5bfts4uvnWK3WMhty5uK6AwoRtT5Y1Yhx6hS/G3meHiM4y3+kKHH7Md9ocmK
                                              XTAjubjDiqZ9xcjnZTtoQSwNSLAWfYG36IMUpOmUQeIQ4TC8rPbgmJB+qBnY74+d
                                              d+RGR8h6rfzVcwRA71TbG58c39C2bmP3+SEWj3+JUyVdUcvdCpGDrLCpK1zEpTF6
                                              iTy40d4tmzmF5gLNYBlaREscpueKAbRmO802rjKBP4AhWBGjKYpm9nv7FdELe6AS
                                              5MgxNZDZ9TSYrUxkhHlLqAYzx6he9xELuckc2eC/SHcvyJHEhgy8iXnElxdTLOSW
                                              H1qfevDF2oPKpXXCONYZ5I3LE5jYdXZqQVEhoLh0dElh+DTpGg16o1UkUEsYVI2v
                                              fjzWwL7QaZeQpspmyY/FsfSKc6kFxH27SufYzZNgZmwNNIvKlBzBPiqvjwWEWsJn
                                              pztnR5qu+chYXav+PmdiuruiJQCMOjimvzltDXg+9EBPKXCVQayS13UBRq7tY+cl
                                              QT73A8poWexuqMKPPWo1CKwcsSOjDQ7zhwiex7flfa0jY12FT7CgL8WkIyAXYYsu
                                              104D74VdDBrPCjH2uhkI9bCzhe9CJpG9wwGtoqi4C1k3a7gDKZr4Ix6uLyqsLLSF
                                              YjqzxGWw7heHOv04uF4ZWgc688qIpTnJbNkY53uiNLitHMGqFzguPx3mgmx4LL7G
                                              LfupN4JHBQrc4g/cdd0VF6rK7BH4FQfoyfkHYW+EF+xIjf2Ku0SecFljR1lfT9Lh
                                              2/EG7qh/4KcwXyoeBha0QzzoxSUXtj9Z7aLzPlN6bGhCst1LpqZloM7uWfQLRgZO
                                              VXCGVF9knT/5JGuJMxmRyq/NedPlxMPTLOLJWRuvq/KQnQhcDjrwr2BfdcoLC1tf
                                              DNhihdwv47lzWzqxRSh0c5Aa54skH3dbp3MCBxusZPPT/aF1pDRDPN1ftSy5LlSy
                                              TaYJK64VwT5LGsLV9vIHZxYsdPKmFTL8NlSLqiNJ3v6vqvZKIZV777bZ8B0stL0h
                                              0PmWvSnlDtzhnx/T/VQ6I/mdHLA5tq+hQG34BSCy8IP88hsJRyeCapVoBvTZs7vS
                                              xjMbPQuQsjbqKz5R0YvgDX55d8XZNtYr5URzYFzOQQN1MX0OTrNmhPO0NUl2YW4g
                                              TWlsaXNhdmxqZXZpYyAoU29uYXR5cGUpIDxjYXJ0bWFuLmRldkBnbWFpbC5jb20+
                                              iQI4BBMBAgAiBQJgC5ZDAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBf
                                              QM28da18lk2PD/wOt0gk0pjVwyRsfDCvW0sFbpR7SDY1o10t73qnQRt97rWv0VQo
                                              GLXpI8w3KdE867STiu+/jS8NkziCqR8+9CkYPbE4E03P2h1yL3b2J/0fzJbxGFwZ
                                              rquKd91BbN62VK8qC53vHD7HqdIp/b18Tc69CecS6hKlH9P782df2oYKGpAadR9l
                                              EaVW2QfdCXgQGpZYpYJR8Cq9jxLE3MkM4qJ3kzEOC4G/g1LyiZjCBzEQa0JRkqqE
                                              H686P/DpbJo4TdmxELtlOoB57HW1p45fV4UP23FNN3u0O4o+2429hKQBkVT+CIsI
                                              OsdmyzhpmYUrGhpOMGjLNo8KkzFmg1VdDAK+hLv+LrsgxG5pyviY03PUnO84zAiN
                                              6BRVZJzFdO67D4zQ/POSIriIDFNSpFNMcuj9EibltoUwDuJmNzJEDhYYC3sx1Tep
                                              p4+fjcbI5Iv/Ikqdzeq4uIs+WXrfh9uWkOz+9Tv8lnCyf12q0SZoXcgPsnXOkBhT
                                              EpqSX2ixPZf1QldwpoXyG30WElFpqe49RiJ8MlBCimnOowtWgL39XmIrj4ra5m62
                                              iILMFyXTSiICD51rsUCBttuYWwDE/ev2XPRH4ySbUDDK6DuPq0Nxun4z/W48/wHU
                                              ep6/n/PNiX++/lq80Vmrrc/5uTfivaGePJalhrRxuqnFDkoyMCyr9VTIqp0HRgRg
                                              C5ZDARAAoo560zKTRHKcyYruF4gF/a8p5F/28EGlWnLg4unEAH/3aS9NPZn/5bLP
                                              DL1t/4J54dj9VSPa5Igm8JI6EKIsi4s5O1m7LRd5TP1lTmFCjgh/1IgTsbueDgIR
                                              9wJMMX0otL08+1XwHKPq3b8tT/2BC9bPutN28XUQpQUPd4z3i7S8sGZBszYdFm62
                                              xsPeo6BsMZAvdLxnmlZlkBDQAQbzEa7Slf+tFOlmt+ZsBnfQQOVxN4dQ5lVqpamY
                                              ZeGdTO8TYVm0rFDEgyojgl+QHbLD7k4c5/7hlVDXnYANjZmwXq4hF09gXug3JdGZ
                                              9bF3XRcUCMv3OMiJxH/gY1oVBlgipb5OR7YdOLLs2syGSs3Mup3uN0SsXCr4RlKF
                                              Ng1dN+kmB3xO/BmAUD2N4CPh2VZlNB5wskCtXjMiHGpaIx/jKSADwu56zPaUSFSs
                                              YvQJgL7nDaCu7YhMCSzXJPiBft1fn5Nz+cQPRD+2lKxbfvaXb9aFFPBipQAHe2V4
                                              fq+R+qpHiubNlF/w4c9fgIA2hmKJ+fTWA+haJSQql2Za/vB4ms8BtY4bP2ucZije
                                              kbTHZERH8QRbhOEURRVp5iEeC3bhYazy4/Nqmmme6cmD8yfs8XHByenrMPx1SmVz
                                              pNtNv41szZJYDpCS7En8bhAz3FL/posStlx4/ag9SDnjr95cGNcAEQEAAf4HAwL9
                                              O1z9QwckzuKj5V2B5v7dcEsofkPQpO1Nzry5JC25pgAwVI2RQEECONkhQmxW/AQ2
                                              e3yRk1ykbz4XDl7sTqC/VNyLltgfa2ALu3qaeKLUgE3yaaqBXqdRxipvZCDGKfz/
                                              8GSWsZtAmKAU6S6JzYqZP6q76fa7rkvdcIlBr/uFtdyC0W2s389SkUikABowynhx
                                              D0GtnnlKo2rltwOT4gw8X3wrzXctmcm66+ZxGmqVO9NPiob7DHuSuprPWBBaOn8E
                                              TZoG9sKoEi01Ei9zHqMJ4kPPCX52jMqEssSV8G+Ov2swqFbjFt7BWj4yjIh8NHO8
                                              dSSMbkx06vVBTJPy48Sw5g3SNxZE4jFs7PS7Kcg5O38kEQU2IWxh975g2txlNzlC
                                              vO2m4D97vQGqJqN4ANv1sSrX7APa1Ww9rCy6pr/zxMpDrpDIsP5gLodng1SbMFpT
                                              1TiGqd/AMWCthFtuG9yL0S5wy05ngHik6pE7QX6lfDNoOctOFUQHB6EyAKJVjKMO
                                              Jfz6NH+o2b5+C5a8xF8aWwQ9tYwHWDI78QU+l3tyIgB7OFmdzce9m0zdC5Z8sisI
                                              gu7fiiFquLIv8zf29mRdmN/nhmOBkM4VJaI1TTZCkIuWnJdXohB/kBtNgYb4R2rG
                                              /Dpl9DdmCHNj74TtGayowvuzPQb84HG/2Z2HwBBYqb0SDBVg6vFGyQg1fpV8XFMu
                                              +IAs4b6d87y4WebsqBte+7t6lTE8xI98UPJF+zk/d81dEtgVpYVjI30YO7HLbOAj
                                              it8AhBUS/kqMxNF0ejczWoffvYoEnKfP2kWY9w4xqLLSYSZvuFErVXQM1vMkOHQR
                                              qaVaKnbpvXig6CH6+dynCkUfWy1deZ2f5jmGfdGg3Ykra1dJYdZhANMDS7ayWD7Q
                                              U25TFyyvU0sK/yo4UpdqdjMQ8iKYJW1gyU2fRlf5oXnsJyoH+SVQNmmJyeEoKjXo
                                              44l8SWBOsOgLCUBMM0PKRONtjJBXxaO4OLxXdx/4UFm/W7MkklcL5tPU0N058nAc
                                              Ikft4zF5eEHMwjmtQBh3RCQkvt/ruw0+7SBPK2PXXk/3chuZnRcEYvqLc6zIt2ie
                                              viDCCSESRjcadRXOsdFlnm8HfRK7OMGJuv+UvxNUQkuzH0JW+upG73v3hjalZVxx
                                              7hfyTo9UTjjKFVNz4tQFxHW294qhvLc9NE7HJ5P1S3Km6f9EpOYWelVdO7K/1NpK
                                              EbJTmPKr4fzf3ohsZ/suOgSgcU49oob2MCbpRoG5jPWJk+cfNQ55iUZcNhNukwW1
                                              te+MY4O3EVU//6RwXN942wxbgQ8rGreyH/rSFB/ffqWYnlHlkxz4pgBX+i6eXDHq
                                              A4LHZcvwbNle9pSIctIEaxH2ySQX7rOlRS6t42wfbE0lkK21hB/5rM4Gczccw31C
                                              mC3XLFdyUZjV/jRtp0N73Kew14HxVdATnDLRMdY1sKw6sKnWbieP2cos2D4covWn
                                              uREClxkOxSbP2ckiXcC+k3XM/UdVu2T1EpScy9yqvrPZls/zBNI4OZGlwnctL8cL
                                              UJcD0VS4cuYmVVVjBZMrXtqXfq+2vUc1IeKymp8qL6pyYCi+NOoJuxcGy4BbEjqG
                                              mUz+JFnIC325JozU/rgwU5Bq8JkjAdJ2HGn/uXmPMkYO7AzkJavFxMxVnACzJk2y
                                              gczF//7fAEguY/G9SBvPfHyqNMejqadGoFYwclX70B/t8nAON//KsKjMw0bH4MxW
                                              Mubb3zxZ3sjo60WB+Mn1P9LUbdF8hK6DmTJCkyBTk0HudvgeiQIfBBgBAgAJBQJg
                                              C5ZDAhsMAAoJEF9Azbx1rXyWZBcP/2/YL3Ht9id5Udy58pIXsNlyBaF4IrmsKKt3
                                              cQCTghHT9Smejqax7+V22FCP37og9AwE0R4pZtZT+2v/dtfXXpLwi3kKTlw3cgbE
                                              3ukNhBLkSEgeNHGr6gIKbEMZ9sr4GRTqe/gwXqt0/Md3z6xjk55cxJkJBHVwFRY7
                                              y3replIlcj+DvyXxf1bMa9JbR3lYduHnXkwVpVBKt7bHAVMJleloPdea00kT0xqs
                                              id/TN63WBgzvLcU12On9EVwSy1SwW43WIP2OFovcb35VDrlGUQBmZBhr/L/kHZxo
                                              6P4uvw5XPFj386M9gBj3a+KXVv+NZB/knRAZpDIJi+wrMrCrmAAZfr7LWYRZKmVq
                                              +TUPfqhbicpgR3UkSWeRNTGigJWkS5PGNYyhjF7biRFphyeTF8hiYby9IxYbDzJm
                                              faUwAFlNy/kaUXNOaH7ir6zRfD0fZ4YGqqObwUPJCxUpbPRl2bGvuN6ZoHb+bJD4
                                              pOfusD1iN9wfcL99eNTVxYH9PZNkR1UeYDJa+IkP54ExRpFrcC1Jn3up0yvW4eqd
                                              LMKzrm3+Ynk6TnPqqS/FhYzRRYDxHhzF2PulXFw8vw0Ty8I5UAvpnXm12ySjlI6O
                                              zUi6k4iL/sHiw70ex4muuZfblyRjsgCi6efr9P8kzP3fFT2xK6wbFPD39l9KkVwS
                                              95jKr7RQ
                                              =kdn+
                                              -----END PGP PRIVATE KEY BLOCK-----"