name: Dev

on:
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/template_check.yml

  test:
    name: Test
    uses: ./.github/workflows/template_test.yml
