name: Production

on:
  push:
    tags:
      - "v*"

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/template_check.yml

  deploy:
    name: Deploy
    needs:
      - verify
    uses: ./.github/workflows/template_deploy.yml
    secrets:
      REPOSITORY_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
      REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}