name: Production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/template_check.yml

  test:
    name: Test
    uses: ./.github/workflows/template_test.yml

  deploy:
    name: Deploy
    needs:
      - verify
    uses: ./.github/workflows/template_deploy.yml
    with:
      STAGE: final
    secrets: inherit