name: Check

on:
  workflow_call:

jobs:
  verify:
    name: Verify gradle plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  build:
    name: Build & test
    runs-on: ubuntu-latest
    needs:
      - verify
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - run: ./gradlew build -x test
      - run: ./gradlew  test
      - uses: test-summary/action@@v2
        with:
          paths: "krang-test/build/test-results/**/TEST-*.xml"
        if: always()