name: Test

on:
  workflow_call:

jobs:
  verify:
    name: Verify gradle plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
  test:
    name: Run integration tests
    runs-on: macos-latest
    needs:
      - verify
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - uses: actions/cache@v4
        with:
          path: ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}
      - name: Run integration tests
        run: ./gradlew -p krang-test allTests --continue